service: appsyncmc-backend
frameworkVersion: "3"

plugins:
  - serverless-appsync-plugin

provider:
  name: aws
  runtime: nodejs12.x

package:
  exclude:
    - package.json
    - yarn.lock

custom:
  appsync:
    - ${file(serverless-appsync-api.yml)}
# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
